apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: locust-slaver
spec:
  selector:
    matchLabels:
      app: locust-slaver
  template:
    metadata:
      labels:
        app: locust-slaver
    spec:
      containers:
      - name:  openpai-locust
        image: albafica/openpai-locust
        imagePullPolicy: Always
        command:
        - "locust"
        - "-H"
        - "${TARGET_URL}"
        - "-f"
        - "/src/stresstest/${SCRIPT_NAME}"
        - "--slave"
        - "--master-host"
        - "${MASTER_URL}"
        env:
        - name: MASTER_URL
          value: ${MASTER_URL}
        - name: TARGET_URL
          value: ${TARGET_URL}
        - name: SCRIPT_NAME
          value: ${SCRIPT_NAME}
